# Generated by Django 2.0.6 on 2018-07-13 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(default='default_image.png', upload_to='wishlist_pic')),
            ],
        ),
        migrations.CreateModel(
            name='WishRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('link_title', models.CharField(default='Recipe', max_length=120)),
                ('wish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist.Wish')),
            ],
        ),
    ]
