# Generated by Django 2.0.6 on 2018-07-16 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='expiration_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
