# Generated by Django 2.0.6 on 2018-07-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('is_bought', models.BooleanField(default=False)),
            ],
        ),
    ]
