# Generated by Django 2.0.6 on 2018-06-19 23:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('made_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('note', models.CharField(max_length=2000)),
                ('picture', models.ImageField(blank=True, upload_to='work_pic')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='work_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Work'),
        ),
    ]
