# Generated by Django 2.0.6 on 2018-07-05 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20180704_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='picture',
            new_name='image',
        ),
    ]
