# Generated by Django 2.0.6 on 2018-07-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20180705_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.FileField(default='default_image.png', upload_to='work_pic'),
        ),
    ]
