# Generated by Django 2.0.6 on 2018-07-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20180711_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, default='default_image.png', null=True, upload_to='work_pic'),
        ),
    ]
